import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  <Head>
    <title>Page Title</title>
    <meta name="description" content="Generated by create next app" />
    <meta
      name="viewport"
      content="width=device-width, minimum-scale=1, initial-scale=1"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:100, 200, 300,400,500,600,700,800,900&display=swap"
    />
    <link rel="icon" href="/favicon.ico" />
  </Head>;
  return <Component {...pageProps} />;
}
